language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database FastFoodFast_test;' -U postgres

script:
  - py.test --cov=app tests/

after_success:
- coveralls